# Generated by Django 3.1.3 on 2020-11-08 09:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(default=datetime.date.today)),
                ('job_status', models.BooleanField(default=False)),
                ('reply', models.IntegerField(default=0)),
                ('replies_from_employer', models.IntegerField(default=0)),
                ('test_tasks', models.IntegerField(default=0)),
                ('offers', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
