# Generated by Django 3.1.3 on 2020-11-08 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_auto_20201108_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='', verbose_name='Коммент'),
        ),
        migrations.AlterField(
            model_name='review',
            name='job_status',
            field=models.BooleanField(default=False, verbose_name='Нашел работу'),
        ),
        migrations.AlterField(
            model_name='review',
            name='offers',
            field=models.IntegerField(default=0, verbose_name='Офферов'),
        ),
        migrations.AlterField(
            model_name='review',
            name='replies_from_employer',
            field=models.IntegerField(default=0, verbose_name='Приглашений'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reply',
            field=models.IntegerField(default=0, verbose_name='Откликов'),
        ),
        migrations.AlterField(
            model_name='review',
            name='test_tasks',
            field=models.IntegerField(default=0, verbose_name='Тестовых'),
        ),
    ]
