# Generated by Django 3.1.3 on 2020-11-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20201108_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='replies_from_employer',
            field=models.IntegerField(default=0, verbose_name='Собеседований'),
        ),
    ]
